In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense, LSTM

In [2]:
data = """ 
About Programme

Business problems need to be jointly addressed by managers and data analysts. Decisions based on analytics need to be made by managers, which they can do only if they understand the data science tools and techniques. Generally, the programmes offered in this domain have focused more on some specific tools and techniques while the business context in which these tools have been applied have received less attention. Hence, a comprehensive programme that focuses both on business knowledge and technical expertise is needed. The IIT and IIMs ‘Master’s in Data Science and Management’ programme will provide better education to future data scientists. The programme will cover general concepts on algorithms, data structures, big data infrastructure, big data analytics life cycle, data security and management, contemporary management thoughts including behavior elements.

Programme Objectives

In today’s environment to remain relevant managers and entrepreneurs need to develop data-driven paradigm to solve new classes of problems which we were not able to solve in the past. Data sciences field is having amazing impact on every aspect of our lives and society.
Education in data science is the key to success and IIT and IIM’s Mater of Science in Data Science and Management programme will provide better education to future data scientists. The programme will cover general concepts on algorithms, data structures, big data infrastructure, big data analytics life cycle, data security and management, contemporary management thoughts including behavior elements. There are four pillars to this programme, i.e., Data, Technology, People, Enterprise Strategy. These pillars are constructed to cultivate the much-required skills for data scientists, i.e., leadership skills, communication skills, eye for business and value, project management, big data analytics life cycle, big data technologies and solutions, data management skills, systems thinking.

Course Content:

The programme structure is divided into six trimesters from basic to advanced courses.The trimester I to trimester IV of the programme will cover the following broad topics:

Advanced Machine Learning
Algorithms
Business Analytics
Business Research
Data Structures
Data Visualization
Database Management System
Design Thinking
Ethics
Financial Management
Generating Business Value with Story Telling and Insights
Human Resource Management
Information Systems for Managers
Introduction to AI
Legal Aspects of Business
Linear Optimization
Machine Learning Foundations
Managerial Communication
Managerial Economics
Marketing Management
Mathematical and Statistical Methods for Data Science – 1
Mathematical and Statistical Methods for Data Science – 2
Operations Management
Organizational Behaviour
Probability and Statistics
Programming Fundamentals for Data Science
Research Methodology
Spreadsheet Modeling
Strategic Management
Supply Chain Management
Understanding Financial Statements and Functions of Finance
In the fifth trimester, participants will be offered a pool of electives to choose from the advanced courses offered by the two Institutes.

In the sixth trimester, participants will also be a part of the project work and will be working under the direction of expert faculty from both the Institutes.

Eligibility

First class (as defined by the awarding Institute/ University) or 60% or 6.0 CPI /6.0 CGPA (on a scale of 10) [relaxation for  SC/ ST/ PwD category as per Government of India rule] degree in
– BTech/ BE/ BS/ BPharm/ BArch/ BDes/BFTech Four years BSc/ MSc/MCA/ MBA

        OR

– Equivalent with having done at least two courses in Mathematics and one in Computer Programming at qualifying degree level.

        AND

CAT/GATE/GMAT/GRE/JAM test score obtained anytime in the last three years
OR

DMAT (Data science and Management Aptitude Test) will be online as well as in physical mode on June 25, 2023.*

The shortlisted candidates will be called for an interview. The final selection will be based on the performance in the interview.

Intake:

Up to 200 candidates will be considered for admission to the programme (Reservation in admissions as per Government of India rules).

Pedagogy:

The teaching will be online with 15 days on-campus modules at both the Institutes.
14 to 15 hours per week live lectures (2 hrs. per day on weekdays and 4-5 hrs. on Saturday).
Lecture timing – 7:00 – 8:00 PM and 8:15 – 9:15 PM on weekdays (tentative).

Lecture timing – 10:45 AM – 11:45 AM, 12:00 noon – 1:00 PM, 2:45 PM – 3:45 PM and 4:00 PM – 5:00 PM on Saturdays (tentative).

The mandatory in-person contact period is planned for one month during the programme.
Important Dates:

Application window opens: April 12, 2023.*
Last date of applications : June 15,2023*
DMAT (Data science and Management Aptitude Test) will be online as well as in physical mode on June 25, 2023.*
Registration will start from: August 07, 2023.*
Classes will start from: August 09, 2023*
*All dates are tentative.

For detailed information please visit the website-  https://msdsm.iiti.ac.in

Contact Us

The Executive Education Office

Indian Institute of Management, Indore, Prabandh Shikhar,
Rau-Pithampur Road,
Indore — 453556
Madhya Pradesh, India
Phone: 0731-2439736/2439666
Email: msdsm-office@iimidr.ac.in

PROGRAMME OVERVIEW
HIGHLIGHTS OF THE PROGRAMME:
2 Years Online Master’s degree programme.
14-15 hours per week live lectures.
Total 900 hours of learning.
Benefit of academic proficiency of faculty from both the Institutes.
30 days on campus during the programme.
Combination of foundational business knowledge, analytical expertise, and big-picture perspective.

PEDAGOGY:
The teaching will be online with 15 days on-campus modules at both the Institutes.
14 to 15 hours per week live lectures (2 hrs. per day on weekdays and 4-5 hrs. on Saturday).
Lecture timing - 7:00 PM - 8:00 PM and 8:15 PM - 9:15 PM on weekdays (tentative).
The mandatory in-person contact period is planned for one month during the programme.
 
DMISSIONS

ELIGIBILITY
First class (as defined by the awarding Institute/ University) or 60% or 6.0 CPI /6.0 CGPA (Scale of 10) [Relaxation for the SC/ ST/ PwD category as per Government of India rule] degree in
BTech/ BE/ BS/ BPharm/ BArch/ BDes/ BFtech/ Four years BSc/ MSc/ MCA/ MBA
OR
Equivalent with having done at least two courses in Mathematics and one in Computer Programming at qualifying degree level.
AND
CAT/GATE/GMAT/GRE/JAM test score obtained anytime in the last three years.
OR
DMAT (Data science and Management Aptitude Test) for those candidates who have not appeared in CAT/GATE/GMAT/GRE/JAM.

DATA SCIENCE AND MANAGEMENT APTITUDE TEST (DMAT)
The Indian Institute of Management Indore and Indian Institute of Technology Indore will jointly conduct Data science and Management Aptitude Test (DMAT) on Sunday, June 25, 2023, in a single session at IIT Indore campus. DMAT will be an OMR- sheet based test. Candidates are not allowed to use mobile phones, calculators etc. during the test. There will be two sections in DMAT
1. Quantitative Ability
2. Data Interpretation and Logical Reasoning
DMAT is of 90 minutes durations and the candidates are expected to solve both these sections within this time. Note that the two sections do not have separate time limits. In order to be considered for interview, candidates need to score above a certain threshold (as decided by the joint committee) in each of the sections. Some sample questions for both the sections will be displayed on the website. Note that these are only indicative, and the actual questions may have a different difficulty level. Candidates are expected to make their own travel and stay arrangements for the test.

SYLLABUS FOR DMAT
1. Quantitative Ability
Commercial Maths
Number Syatem
Set Theory/Venn Diagram
Functions
Inequalities
Geometry
Coordinate Geometry
Trigonometry
Matrices
Progression
Probability/Statistics (class X level)
Logarithm
Permutaion and Combination
Basic Algebra
Polynomials/Equations/Roots
Ratio and Proportions
Miscellaneous
2. Data Interpretation and Logical Reasoning
IMPORTANT DATES
Online Application will start from: April 12, 2023.
Last date of applications: June 15, 2023.
Extended deadline for applications:: June 20, 2023.
Registration will start from: August 7, 2023.

HOW TO APPLY
Register on the website: Link will be opened on April 12, 2023
APPLICATION FEE
For Indian Applicants	For International Applicants (Including OCI/PIO/NRI))	Remarks
₹1770/- (Including GST)	₹2300/- (Including GST)	CAT/GATE/GMAT/GRE/JAM test score obtained anytime in the last three years.
₹2360/- (Including GST)	₹2890/- (Including GST)	Those who intend to appear in DMAT.
ABOUT IIT INDORE
MISSION
The 21st century heralded the age of knowledge societies. Indian Institute of Technology Indore, established in 2009, in the tradition of the IITs as a center for excellent education and training in IIT Indore aims to play an active role in this task of propelling India on her growth-trajectory by focusing on education, research and development. IIT Indore’s motto Vidya Sarvajana hitaya reflects the mission of the institute-education for the benefit and reach of all.

VISION
Academics:
A vibrant academic community that develops programmes and research projects across disciplines.
To facilitate extensive hands-on training by developing sophisticated instrumentation and experimental facilities and nurture creative scientific thinking.
Adjunct faculty and distinguished international visiting faculty to form important components of the institute’s teaching and research profile.
Research and Development:
Promote interdisciplinary research in science, engineering, and humanities and social sciences.
Conduct disruptive and social impacting research in some chosen areas such as sustainable development, climate change, food and water security.
Promote industry-oriented research leading to new products, processes, and technologies.
Promote culture of start-ups and entrepreneurship by establishing Industrial Research Park which will be a focal point in Central India.
Aggressive patenting and protection of IPR.
Innovation and Entrepreneurship:
“Concept to Product” to be facilitated with heavy engagement with industry partners.
Promote undergraduate research, start–ups and incubators within the campus.
ABOUT IIM INDORE
With the objective of imparting high quality management education and training, the Department of Higher Education, Ministry of Education, Government of India established Indian Institute of Management Indore as one of the Institutions of Excellence. These Institutions are recognized as premier management institutions, comparable to the best in the world for teaching, research, and interaction with industries.

Established in 1996, Indian Institute of Management Indore (IIM Indore) has been a leader in the field of management education, interfacing with the industry, Government and PSUs. It is promoted and nurtured by the Ministry of Education, Government of India and is an institute of national importance under the Indian Institutes of Management Act, 2017.

IIM Indore has the latest in teaching aids, rich learning resources, a strong IT backbone, state-of-the-art sports complex and hostels as well as contemporary infrastructure.

IIM Indore Rankings:

Ranked in Top 100 in FT Rankings 2021, 4th in India and 3rd amongst the IIMs
25th Rank in the Global MBA QS Ranking in Asia, 4th amongst the IIMs

MISSION
IIM Indore seeks to be a contextually relevant business school with world-class academic standards that develops socially-conscious managers, leaders, and entrepreneurs. IIM Indore is committed to:

Excellence in management education, research, and training.
Use of contemporary participant-centric pedagogies and teaching methods.
A presence in emerging segments of management education.

MODE OF TEACHING AND EVALUATION
The teaching will be online with campus modules at both the Institutes. There will be 14 to 15 hours per week live lectures (2 hrs per day on weekdays and 4 -5 hrs on Saturday). The timing for weekdays will be tentatively 7:00 PM - 8:00 PM and 8:15 PM - 9:15 PM. The evaluation will be continuous with online assignment and quizzes. Also, there will be End-trimesters examination. The mandatory in-person contact period is planned for one month during the programme. This will be splited in two blocks of 15 days each. This will provide in-person interaction and access to other research facilities.
Project Work: In the last trimester, student will have to do a project and submit the report for award towards the degree.


AWARDING DEGREE

Joint degree on MS in Data Science and Management will be awarded by IIT Indore and IIM Indore.
SELECTION PROCESS
The shortlisted candidates will be called for an interview. The final selection will be based on the performance in the interview.
A joint committee, consisting of the expert faculty members from IIM Indore and IIT Indore will conduct the interview process.

ELIGIBILITY AND INTAKE
ELIGIBILITY
First class (as defined by the awarding Institute/ University) or 60% or 6.0 CPI /6.0 CGPA (Scale of 10) [Relaxation for the SC/ ST/ PwD category as per Government of India rule] degree in
BTech/ BE/ BS/ BPharm/ BArch/ BDes/ BFtech/ Four years BSc/ MSc/ MCA/ MBA
OR
Equivalent with having done at least two courses in Mathematics and one in Computer Programming at qualifying degree level.
AND
CAT/GATE/GMAT/GRE/JAM test score obtained anytime in the last three years.
OR
DMAT (Data Science and Management Aptitude Test) will be online as well as in physical mode on June 25, 2023.


The shortlisted candidates will be called for an interview. The final selection will be based on the performance in the interview.

INTAKE
Up to 200 candidates will be considered for admission to the programme.
(Reservation in admissions as per Government of India rules)

COURSE CONTENTS
The programme structure is divided into six trimesters from basic to advanced courses.

The trimester I to trimester IV of the programme will cover the following broad topics:
Probability and Statistics
Programming and Data Structures
Mathematical and Statistical Methods
Database Management System
Machine Learning: Foundation to Advanced
Artificial Intelligence: Foundation to Advanced
Research Methodology
Managerial Communication
Optimization
Managerial Economics
Organizational Behavior
Operations and Supply Chain Management
Marketing Management
Financial Statements and Financial Management
Human Resource Management
Strategic Management
Information Systems
Ethics
Legal Aspects of Business
Business Analytics
Data Visualization and Storytelling
and many more...

In the fourth and fifth trimester, participants will be offered a pool of electives to choose from the advanced courses offered by the two Institutes.

In the sixth trimester, participants will undertake a project under the guidance of faculty expertise from both the Institutes.

PROGRAMME OBJECTIVES
FOUR PILLARS OF THE PROGRAMME
Data
Enterprise Strategy
Technology
People

LEARNING OUTCOMES
The programme positions students to transform data into better business decisions.
Students will be able to both identify areas of business where data science can add value and provide inputs to algorithm developers and data analysts.
An effective cluster of foundational business knowledge, analytical expertise, and big picture perspective.
The programme will help to translate data analysis into actionable insights and provide recommendations to create business impact.
APPLICATION AND PROGRAMME FEE DETAILS

APPLICATION FEE
For Indian Applicants	For International Applicants (Including OCI/PIO/NRI))	Remarks
₹1770/- (Including GST)	₹2300/- (Including GST)	CAT/GATE/GMAT/GRE/JAM test score obtained anytime in the last three years.
₹2360/- (Including GST)	₹2890/- (Including GST)	Those who intend to appear in DMAT.

PROGRAMME FEE
Programme Fee: INR 12.0 Lakhs (Indian participants)/ INR 15.6 Lakhs (International participants)
The fee for the programme will be collected in three equal installments.
First installment will be collected at the start of the programme (for 1st and 2nd trimesters).
Second installment will be collected before the commencement of the 3rd trimester (for 3rd and 4th trimesters).
Third installment will be collected before the commencement of the 5th trimester (for 5th and 6th trimesters).
Pay Program Fee (Acceptance Fee /Trimester Fee) Batch-1: Click here
Pay Program Fee (Acceptance Fee /Trimester Fee) Batch-2: Click here


*Application fee is non-refundable

EMAIL US
msdsm-office@iimidr.ac.in
msdsm-office@iiti.ac.in
Please note that IIM Indore reserves the right to change the programme design, format, number of sessions, certificate format, terms in the programme or can incorporate any such change deemed necessary by the institute without prior intimation.
"""

In [3]:
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts([data])

In [5]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'in': 3,
 'of': 4,
 'to': 5,
 'will': 6,
 'data': 7,
 'be': 8,
 'management': 9,
 'for': 10,
 'on': 11,
 'programme': 12,
 'as': 13,
 'indore': 14,
 'a': 15,
 'science': 16,
 'business': 17,
 '15': 18,
 'research': 19,
 'pm': 20,
 'by': 21,
 'education': 22,
 'with': 23,
 'test': 24,
 'is': 25,
 'trimester': 26,
 'or': 27,
 '2023': 28,
 'fee': 29,
 'including': 30,
 'from': 31,
 '–': 32,
 'institute': 33,
 'per': 34,
 'dmat': 35,
 'india': 36,
 'at': 37,
 'both': 38,
 'degree': 39,
 'candidates': 40,
 '00': 41,
 'indian': 42,
 '2': 43,
 'institutes': 44,
 'years': 45,
 'online': 46,
 'iim': 47,
 'iit': 48,
 'big': 49,
 'are': 50,
 'two': 51,
 'government': 52,
 'last': 53,
 'interview': 54,
 'teaching': 55,
 'gst': 56,
 'have': 57,
 'advanced': 58,
 'courses': 59,
 '6': 60,
 '0': 61,
 'one': 62,
 'june': 63,
 'an': 64,
 'analytics': 65,
 'this': 66,
 'that': 67,
 'trimesters': 68,
 'learning': 69,
 'participants': 70,
 'faculty': 71,
 'cat': 72,
 'gate': 73,
 'gm

In [6]:
len(tokenizer.word_index)

755

In [7]:
input_sequence = []
for sentence in data.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(tokenized_sentence)):
        n_gram = tokenized_sentence[:i+1]
        input_sequence.append(n_gram)

In [8]:
max_length = max([len(x) for x in input_sequence])

In [9]:
max_length

129

In [10]:
padded_input_sequences = pad_sequences(input_sequence, maxlen=max_length, padding='pre')

In [11]:
padded_input_sequences

array([[  0,   0,   0, ...,   0, 150,  12],
       [  0,   0,   0, ...,   0,  17, 242],
       [  0,   0,   0, ...,  17, 242, 103],
       ...,
       [  0,   0,   0, ...,   1,  33, 753],
       [  0,   0,   0, ...,  33, 753, 754],
       [  0,   0,   0, ..., 753, 754, 755]])

In [12]:
X = padded_input_sequences[: , :-1]
X

array([[  0,   0,   0, ...,   0,   0, 150],
       [  0,   0,   0, ...,   0,   0,  17],
       [  0,   0,   0, ...,   0,  17, 242],
       ...,
       [  0,   0,   0, ...,  21,   1,  33],
       [  0,   0,   0, ...,   1,  33, 753],
       [  0,   0,   0, ...,  33, 753, 754]])

In [13]:
y= padded_input_sequences[: , -1]
y

array([ 12, 242, 103, ..., 753, 754, 755])

In [14]:
#multiclass classification problem, softmax

In [15]:
X.shape

(2361, 128)

In [16]:
y.shape

(2361,)

In [17]:
y = to_categorical(y, num_classes=756)

In [18]:
X.shape

(2361, 128)

In [19]:
y.shape

(2361, 756)

In [20]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [21]:
model = Sequential()

In [22]:
model.add(Embedding(756,100,input_length = 128))
model.add(LSTM(160))
model.add(Dense(756, activation = 'softmax'))

In [23]:
model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics = 'accuracy')

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 128, 100)          75600     
                                                                 
 lstm (LSTM)                 (None, 160)               167040    
                                                                 
 dense (Dense)               (None, 756)               121716    
                                                                 
Total params: 364356 (1.39 MB)
Trainable params: 364356 (1.39 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
model.fit(X,y,epochs = 40)

Epoch 1/40
74/74 [==============================] - 12s 144ms/step - loss: 6.1765 - accuracy: 0.0313
Epoch 2/40
74/74 [==============================] - 12s 156ms/step - loss: 5.7861 - accuracy: 0.0449
Epoch 3/40
74/74 [==============================] - 12s 161ms/step - loss: 5.6829 - accuracy: 0.0517
Epoch 4/40
74/74 [==============================] - 11s 154ms/step - loss: 5.5415 - accuracy: 0.0779
Epoch 5/40
74/74 [==============================] - 11s 149ms/step - loss: 5.3547 - accuracy: 0.0974
Epoch 6/40
74/74 [==============================] - 10s 141ms/step - loss: 5.0571 - accuracy: 0.1283
Epoch 7/40
74/74 [==============================] - 10s 141ms/step - loss: 4.6387 - accuracy: 0.1681
Epoch 8/40
74/74 [==============================] - 10s 138ms/step - loss: 4.2045 - accuracy: 0.2410
Epoch 9/40
74/74 [==============================] - 10s 141ms/step - loss: 3.7955 - accuracy: 0.3045
Epoch 10/40
74/74 [==============================] - 10s 140ms/step - loss: 3.4312 - accura

In [26]:
text = "mail"

In [31]:
token_text = tokenizer.texts_to_sequences([text])[0]

In [36]:
padded_tok_sequence = pad_sequences([token_text], maxlen=128, padding='pre')

In [37]:
padded_tok_sequence

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
model.predict(padded_tok_sequence)

1/1 [==============================] - 0s 439ms/step


array([[2.68312448e-07, 8.35945830e-04, 3.79245705e-03, 2.79221758e-02,
        6.83208928e-03, 6.54650386e-04, 1.89138018e-03, 3.17888567e-03,
        5.80026535e-05, 5.45225032e-02, 4.04347479e-03, 6.38073951e-04,
        7.58717488e-03, 1.73836877e-03, 6.91722962e-04, 8.05282471e-05,
        8.29132448e-04, 3.01735243e-03, 1.21227617e-03, 3.27070034e-03,
        1.06596808e-05, 8.44628812e-05, 7.97317887e-04, 8.22285935e-03,
        2.65862502e-04, 2.84273271e-03, 4.12230322e-04, 2.53679882e-05,
        3.35656000e-06, 2.09177975e-02, 9.08114016e-04, 4.58389586e-05,
        6.96444185e-04, 1.04999449e-03, 9.30603273e-05, 4.62971861e-04,
        7.74875458e-04, 5.32462800e-05, 1.82383119e-05, 5.05725332e-02,
        8.66554910e-04, 9.13870972e-05, 1.00136362e-02, 4.90495004e-05,
        4.09858294e-05, 4.23215749e-03, 1.88218628e-03, 1.77781959e-03,
        1.82263408e-04, 3.94888106e-04, 1.95981542e-04, 7.76981833e-05,
        9.56806107e-05, 7.52449923e-05, 1.06077081e-04, 4.927205

In [39]:
model.predict(padded_tok_sequence).shape

1/1 [==============================] - 0s 19ms/step


(1, 756)

In [48]:
pos = np.argmax(model.predict(padded_tok_sequence)) #gives the position of argmax value
pos

1/1 [==============================] - 0s 19ms/step


171

In [42]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'in': 3,
 'of': 4,
 'to': 5,
 'will': 6,
 'data': 7,
 'be': 8,
 'management': 9,
 'for': 10,
 'on': 11,
 'programme': 12,
 'as': 13,
 'indore': 14,
 'a': 15,
 'science': 16,
 'business': 17,
 '15': 18,
 'research': 19,
 'pm': 20,
 'by': 21,
 'education': 22,
 'with': 23,
 'test': 24,
 'is': 25,
 'trimester': 26,
 'or': 27,
 '2023': 28,
 'fee': 29,
 'including': 30,
 'from': 31,
 '–': 32,
 'institute': 33,
 'per': 34,
 'dmat': 35,
 'india': 36,
 'at': 37,
 'both': 38,
 'degree': 39,
 'candidates': 40,
 '00': 41,
 'indian': 42,
 '2': 43,
 'institutes': 44,
 'years': 45,
 'online': 46,
 'iim': 47,
 'iit': 48,
 'big': 49,
 'are': 50,
 'two': 51,
 'government': 52,
 'last': 53,
 'interview': 54,
 'teaching': 55,
 'gst': 56,
 'have': 57,
 'advanced': 58,
 'courses': 59,
 '6': 60,
 '0': 61,
 'one': 62,
 'june': 63,
 'an': 64,
 'analytics': 65,
 'this': 66,
 'that': 67,
 'trimesters': 68,
 'learning': 69,
 'participants': 70,
 'faculty': 71,
 'cat': 72,
 'gate': 73,
 'gm

In [52]:
text = "about"
for i in range(2):
    token_text = tokenizer.texts_to_sequences([text])[0]
    padded_tok_sequence = pad_sequences([token_text], maxlen=128, padding='pre')
    pos = np.argmax(model.predict(padded_tok_sequence))
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " "+ word
            print(text)

1/1 [==============================] - 0s 18ms/step
about iim
1/1 [==============================] - 0s 18ms/step
about iim indore
